# Generated by Django 5.2.14 on 2026-05-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="floor_label",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="unit",
            name="is_roof_level",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="position_on_floor",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
